import { randomUUID } from 'node:crypto';
import {
  applyHistoryLength,
  isLegalTransition,
  isTerminal,
  type Artifact,
  type Message,
  type Task,
  type TaskState,
} from './spec.js';

/**
 * Task state, and the lifecycle it is allowed to move through.
 *
 * The specification defines the states (§4.1.3), which of them are terminal and
 * which are interrupted, but it publishes no edge list; `LEGAL_TASK_TRANSITIONS`
 * in `spec.ts` derives one from those facts and explains the derivation. This
 * file is what enforces it.
 *
 * Enforcing it at all is the point. Every state change in this package goes
 * through `transition`, which refuses an illegal one by throwing rather than by
 * writing it and moving on. A task that has already reported
 * `TASK_STATE_COMPLETED` to a caller must not later report
 * `TASK_STATE_WORKING`: an orchestrator that saw the first has already acted on
 * it, and a lifecycle that can run backwards is one nothing downstream can rely
 * on. A thrown error here is a bug in this connector and reaches the caller as
 * an internal error; a silently accepted backwards transition would reach the
 * caller as a lie.
 */

export class IllegalTaskTransition extends Error {
  constructor(
    readonly taskId: string,
    readonly from: TaskState,
    readonly to: TaskState,
  ) {
    super(`task ${taskId} cannot move from ${from} to ${to}`);
    this.name = 'IllegalTaskTransition';
  }
}

export interface TaskRecord {
  readonly id: string;
  readonly contextId: string;
  state: TaskState;
  /** The status message, when the state change carried one. */
  statusMessage: Message | undefined;
  /** ISO 8601, UTC (§5.6.1). Updated on every transition. */
  statusTimestamp: string;
  readonly artifacts: Artifact[];
  readonly history: Message[];
  /** Insertion order, so listings are stable and pagination means something. */
  readonly sequence: number;
}

export interface ListFilter {
  contextId?: string | undefined;
  status?: TaskState | undefined;
  statusTimestampAfter?: string | undefined;
  pageSize?: number | undefined;
  pageToken?: string | undefined;
  historyLength?: number | undefined;
  includeArtifacts?: boolean | undefined;
}

export interface ListPage {
  tasks: Task[];
  nextPageToken: string;
  pageSize: number;
  totalSize: number;
}

/** Proto `ListTasksRequest.page_size`: "If unspecified, at most 50 tasks will be returned." */
export const DEFAULT_PAGE_SIZE = 50;
/** Proto `ListTasksRequest.page_size`: "The maximum value is 100." */
export const MAX_PAGE_SIZE = 100;

export interface TaskStoreOptions {
  now?: () => number;
  /**
   * How many tasks to retain.
   *
   * A connector that never forgets a task is a connector that leaks memory for
   * as long as it runs, and this one is meant to sit behind an agent
   * orchestrator that may drive thousands of runs. When the ceiling is reached
   * the oldest *terminal* tasks are dropped first and non-terminal ones are
   * never dropped, because a task still in flight is one a caller is still
   * waiting on. A caller that asks for an evicted task gets
   * `TaskNotFoundError`, which the specification already describes as the
   * answer for a task that "might be invalid, expired, or already completed and
   * purged" (§3.3.2).
   */
  maxTasks?: number;
}

export const DEFAULT_MAX_TASKS = 10_000;

export class TaskStore {
  readonly #tasks = new Map<string, TaskRecord>();
  readonly #now: () => number;
  readonly #maxTasks: number;
  #sequence = 0;

  constructor(options: TaskStoreOptions = {}) {
    this.#now = options.now ?? Date.now;
    this.#maxTasks = options.maxTasks ?? DEFAULT_MAX_TASKS;
  }

  get size(): number {
    return this.#tasks.size;
  }

  /**
   * Open a task in `TASK_STATE_SUBMITTED`.
   *
   * §3.4.2 lets a client supply the task id it wants to continue, but a *new*
   * task's id is the server's to mint — the proto says so on `Task.id`
   * ("generated by the server for a new task"). Accepting a client-chosen id
   * for a new task would let one caller collide with, or address, another's.
   */
  create(contextId: string | undefined, message: Message): TaskRecord {
    const id = randomUUID();
    const record: TaskRecord = {
      id,
      contextId: contextId ?? randomUUID(),
      state: 'TASK_STATE_SUBMITTED',
      statusMessage: undefined,
      statusTimestamp: this.#timestamp(),
      artifacts: [],
      history: [{ ...message, taskId: id }],
      sequence: (this.#sequence += 1),
    };
    this.#tasks.set(id, record);
    this.#evict();
    return record;
  }

  get(id: string): TaskRecord | undefined {
    return this.#tasks.get(id);
  }

  /** Move a task, or refuse. See the note on `IllegalTaskTransition` above. */
  transition(id: string, to: TaskState, statusMessage?: Message): TaskRecord {
    const record = this.#tasks.get(id);
    if (!record) throw new IllegalTaskTransition(id, 'TASK_STATE_UNSPECIFIED', to);
    if (!isLegalTransition(record.state, to)) throw new IllegalTaskTransition(id, record.state, to);
    record.state = to;
    record.statusMessage = statusMessage;
    record.statusTimestamp = this.#timestamp();
    if (statusMessage) record.history.push(statusMessage);
    return record;
  }

  /** Append a client message to a task already in flight (§3.4.3). */
  appendMessage(id: string, message: Message): TaskRecord | undefined {
    const record = this.#tasks.get(id);
    if (!record) return undefined;
    record.history.push({ ...message, taskId: id });
    return record;
  }

  addArtifact(id: string, artifact: Artifact): void {
    this.#tasks.get(id)?.artifacts.push(artifact);
  }

  /**
   * Render a record as the wire `Task` (§4.1.1).
   *
   * `history` and `artifacts` are omitted rather than sent empty when there is
   * nothing to say: §5.7 tells implementations to distinguish set from unset,
   * and an empty array is a claim ("this task produced no artifacts") that is
   * only true once the task is terminal.
   */
  snapshot(record: TaskRecord, options: { historyLength?: number | undefined; includeArtifacts?: boolean } = {}): Task {
    const history = applyHistoryLength(record.history, options.historyLength);
    const includeArtifacts = options.includeArtifacts ?? true;
    return {
      id: record.id,
      contextId: record.contextId,
      status: {
        state: record.state,
        ...(record.statusMessage ? { message: record.statusMessage } : {}),
        timestamp: record.statusTimestamp,
      },
      ...(includeArtifacts && record.artifacts.length > 0 ? { artifacts: [...record.artifacts] } : {}),
      ...(history && history.length > 0 ? { history } : {}),
    };
  }

  /**
   * §3.1.4 / §9.4.4. Filter, then page.
   *
   * The page token is the sequence number of the last task on the previous
   * page, not an offset. An offset would silently skip or repeat rows when a
   * task is created or evicted between two pages, which for a caller walking a
   * long list looks like data loss rather than like concurrency.
   */
  list(filter: ListFilter = {}): ListPage {
    const pageSize = Math.min(filter.pageSize ?? DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE);
    const after = decodePageToken(filter.pageToken);

    const matching = [...this.#tasks.values()]
      .filter((record) => {
        if (filter.contextId !== undefined && record.contextId !== filter.contextId) return false;
        if (filter.status !== undefined && record.state !== filter.status) return false;
        if (filter.statusTimestampAfter !== undefined && record.statusTimestamp < filter.statusTimestampAfter) {
          return false;
        }
        return true;
      })
      .sort((a, b) => a.sequence - b.sequence);

    const page = matching.filter((record) => record.sequence > after).slice(0, pageSize);
    const last = page.at(-1);
    const more = last !== undefined && matching.some((record) => record.sequence > last.sequence);

    return {
      tasks: page.map((record) =>
        this.snapshot(record, {
          historyLength: filter.historyLength,
          // Proto `ListTasksRequest.include_artifacts`: "Defaults to false to
          // reduce payload size." A ForgeBridge diff artifact carries whole
          // script sources, so this default is worth honouring precisely.
          includeArtifacts: filter.includeArtifacts ?? false,
        }),
      ),
      nextPageToken: more && last ? encodePageToken(last.sequence) : '',
      pageSize,
      totalSize: matching.length,
    };
  }

  #timestamp(): string {
    return new Date(this.#now()).toISOString();
  }

  #evict(): void {
    if (this.#tasks.size <= this.#maxTasks) return;
    for (const [id, record] of this.#tasks) {
      if (this.#tasks.size <= this.#maxTasks) return;
      if (isTerminal(record.state)) this.#tasks.delete(id);
    }
  }
}

/**
 * The token is opaque to clients by contract, so it is encoded rather than sent
 * as a bare number: a client that reads a decimal cursor will start doing
 * arithmetic on it, and then the encoding cannot change.
 */
export function encodePageToken(sequence: number): string {
  return Buffer.from(String(sequence), 'utf8').toString('base64url');
}

export function decodePageToken(token: string | undefined): number {
  if (!token) return 0;
  const decoded = Number(Buffer.from(token, 'base64url').toString('utf8'));
  // A malformed token reads as "from the beginning" rather than throwing. It is
  // a cursor into a listing, not an authorisation, so the safe failure is a
  // repeated page.
  return Number.isSafeInteger(decoded) && decoded >= 0 ? decoded : 0;
}
